# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Branches

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn test
      env:
        CI: true
    - run: yarn build
      working-directory: ./webpack
    - run: yarn setup-github-actions
      working-directory: ./webpack
    - run: yarn test
      working-directory: ./webpack
    - run: yarn build
      working-directory: ./cjs-test
    - run: yarn test
      working-directory: ./cjs-test
    - run: yarn build
      working-directory: ./esm-test
    - run: yarn test
      working-directory: ./esm-test
